### ISSUE TITLE
Some Errors Not Outputted

### ISSUE THREAD

**Issue by mswieboda** [jwo/ruby-fiddle-web#21]
Currently some syntax error messages are not outputted. http://rubyfiddle.com/riddles/7d53e 

The errors seem to be more with basics in syntax and correctly structured Ruby code. Name errors such as variables not existing output fine: http://rubyfiddle.com/riddles/37fb5/2

Haven't taken a look at any code, but https://github.com/jwo/ruby-fiddle-exec seems to output exception in the JSON, maybe I can fork and take a look when I have a chance to fufill my curiousity.

**Comment by mswieboda** [comment]
I probably should close this for now, I inspected https://github.com/jwo/ruby-fiddle-exec a little and saw 

```ruby
it "shouldn't throw a syntax error" do
```

in the specs, so assuming the execution doesn't output them for now. Maybe I'll dive more later, but having problems with https://github.com/jwo/jruby-sandbox 

````
Sandbox::SandboxException:
  NameError: uninitialized constant FakeFS::Dir
# sandbox/SandboxFull.java:75:in `eval'
# ./lib/riddle.rb:22:in `safe_evaluation'
# ./lib/riddle.rb:12:in `execute'
# ./spec/riddle_spec.rb:25:in `(root)'
````

when I uncomment the `rescue` in `Riddle#safe_evaluation`
